# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformTaskV3@3
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: 'Terraform'
      backendServiceArm: 'trainingServiceConnection'
      backendAzureRmResourceGroupName: 'storrage'
      backendAzureRmStorageAccountName: 'storragealeks'
      backendAzureRmContainerName: 'terraform'
      backendAzureRmKey: 'tf/terraform.tfstate'
  - task: TerraformTaskV3@3
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      workingDirectory: 'Terraform'
      environmentServiceNameAzureRM: 'trainingServiceConnection'
