apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-app
spec:
  selector:
    matchLabels:
      app: greetings-app
  #Update deployment for Greetings app to run 4 replicas of application.
  replicas: 4
  template:
    metadata:
      labels:
        app: greetings-app
    spec:
      containers:
      - name: greetings-app
        #Update deployment for the Greetings app with the path to your container registry and your container image.
        image: aliakseikastsiuk.azurecr.io/app:latest
      #use configmap as an env variable in deployment for the Greetings app
        envFrom:
         - configMapRef:
            name: configmap
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        #update deployment to utilize secret
      imagePullSecrets:
      - name: secret
#create Secret of kubernetes.io/dockerconfigjson type to authenticate with a container registry.
##kubectl create secret docker-registry kuber-secret --docker-server=aliakseikastsiuk.azurecr.io --docker-username=AliakseiKastsiuk --docker-password=Mr1kKxy0hnzAU7VFq/FNjx+r/lJKkL5R
      #Greetings application should utilize "frontendPool" node pool.
      nodeSelector:
        agentpool: frontendpool